policies:
  - name: CloudTrailConfigurationchangesAlarm_Validated
    resource: alarm
    filters:
      - type: value
        key: MetricName
        op: eq
        value: CloudTrailConfigurationChanges